import React from 'react'
import styled from "styled-components"
const AboutMe = () => {
  return (
    <Introduction>
        <div className="about"> <h1  >One's Own:</h1>
            <div className="intro">I'm Aman, currently pursuing a BTech in Electrical 
        Engineering at the National Institute of Technology Hamirpur,
         though my heart is set on the IT sector, particularly web design.
          Despite my major, I've been self-studying web development, learning HTML, 
          CSS, and JavaScript along with DSA. Additionally, I've ventured into
           multimedia, excelling in photo and video editing. My aim is
            to blend my technical and creative skills to contribute innovative
             solutions to the IT field. This unique perspective, coupled with my
            engineering foundation, positions me to approach
         challenges from multiple angles. I'm enthusiastic about the prospect
         of applying my skills and knowledge in this dynamic industry.
            </div>
            <div className="techskills">
                <div className="lang"> <h3>Programming Languages</h3>
                   <ul>
                         <li>HTML & CSS</li>
                         <li>JavaScript</li>
                         <li>C & C++</li>
                     </ul>
                </div>

                <div className='frame' >
                    <h3>Frameworks</h3>
                        <ul>
                           <li>Bootstrap</li>
                           <li>React</li>
                        </ul> 
                </div>

                <div className='courses' >
                    <h3>Key Courses</h3>
                    <ul>
                        <li>Data Structures and Algorithms</li>
                        <li>Web Development (Front-end)</li>
                        <li>Object-Oriented Programming (OOPs)</li>
                    </ul>
                </div>

                <div className='multi'>
                   <h3>Multimedia</h3>
                   <ul>
                       <li>Photo Editing using Adobe Photoshop</li>
                       <li>Video Editing using Edius & Adobe Premier Pro</li>
                   </ul>
                </div>

                <div className='endself' >
                I possess a practical skill set in web development, 
                encompassing front-end technologies such as HTML, CSS, 
                and JavaScript, along with popular frameworks like React 
                and Bootstrap. My coursework has equipped me with a 
                strong foundation in data structures and algorithms, 
                which I apply to problem-solving in programming.
                </div>
            </div>
     
        </div> 
        
        

    </Introduction>
  )
}

export default AboutMe

const Introduction = styled.div`
padding-top: 70px;
.about{
    width: 100%;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    gap:15px;
}
    h1{ 
        font-size: 45px;
        color: #9440e2;
        background-color: #201d5e4f;
        border-radius: 10px;
        padding: 10px 50px;
        font-family: 'Signika Negative', sans-serif;
         
    }
    .intro{
        width: 80%;
        padding: 20px 0px;
        color: white;
        font-size: 1.3rem;
        font-family: sans-serif;
        line-height: 1.5;
        margin: 0 auto;
    }
    .techskills{
        display: flex;
        flex-direction: column;
        width: 80%;
        margin: 0 auto;
    }
    .lang,.frame,.multi,.courses{
        h3{
            font-size: 20px;
            color: #9440e2;
            background-color: #201d5e4f;
            border-radius: 10px;
            padding: 10px 20px;
            margin: 20px 0;
            font-family: 'Signika Negative', sans-serif;
        }
        li{
            color: white;
            list-style: none;
            font-size: 1.1rem;
            font-family: sans-serif;
            margin: 15px 0px;
            padding: 5px 40px;
        }
    }

    .endself{
        padding: 20px 0px;
        color: white;
        font-size: 1.3rem;
        font-family: sans-serif;
        line-height: 1.5;
        margin-bottom: 40px;
    }
    .tracking-in-contract-bck{-webkit-animation:tracking-in-contract-bck 1s cubic-bezier(.215,.61,.355,1.000) both;animation:tracking-in-contract-bck 1s cubic-bezier(.215,.61,.355,1.000) both}

 /* ----------------------------------------------
 * Generated by Animista on 2023-10-13 16:32:20
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes tracking-in-contract-bck{0%{letter-spacing:1em;-webkit-transform:translateZ(400px);transform:translateZ(400px);opacity:0}40%{opacity:.6}100%{-webkit-transform:translateZ(0);transform:translateZ(0);opacity:1}}@keyframes tracking-in-contract-bck{0%{letter-spacing:1em;-webkit-transform:translateZ(400px);transform:translateZ(400px);opacity:0}40%{opacity:.6}100%{-webkit-transform:translateZ(0);transform:translateZ(0);opacity:1}}
    
`