import React from 'react'
import styled from "styled-components"
import {useTypewriter,Cursor} from "react-simple-typewriter"
const MainBody = () => {

    const [text] = useTypewriter({
        words:["Web Developer !","Web Designer !","Photo Editor !","Video Editor !"],
        loop:{},
        typeSpeed:100,
        delaySpeed:3000
    });
    
  return (
    <BodySection>
        <div className='bodycontainer'  >
            <div className='leftsection scale-in-center '>
                <div >Hi, My name is <span className='aman' >Aman</span> </div>
                <div>I am a passionate</div>
                 <span className='profile' >{text} <Cursor/> </span> 
                <div className="mButtons">
                    <div className="uprbtn">
                            <a href = "./images/AmanResume2.pdf" download  >  
                                  <p>download resume </p>  
                             </a> 
                             <a href = "https://www.linkedin.com/in/aman-gadwal-126639214/" target="_blank" >  
                                   <p>Visit Linkedin </p>  
                              </a> 
                    </div>
                    
                    <div className="lowbtn">
                            <a href = "https://auth.geeksforgeeks.org/user/20beevxfl/practice" target="_blank">  
                                   <p>Visit Gfg </p>  
                              </a> 
                              <a href = "https://github.com/AmanGadwal29" target="_blank">  
                                   <p>Visit Github </p>  
                              </a>
                    </div>
                       
                </div>
                
                  
            </div>
            <div className='rightsection  '>
                <img className='scale-in-center' src="./images/bg.png" alt="" />
            </div>
            
        </div>

    </BodySection>
  )
}

export default MainBody

const BodySection = styled.div`
    .bodycontainer{
        
        padding-top: 120px;
        display: flex;
        /* background-color: #01012d; */
        justify-content: space-around;
    }
    .scale-in-center{-webkit-animation:scale-in-center .5s cubic-bezier(.25,.46,.45,.94) both;animation:scale-in-center .5s cubic-bezier(.25,.46,.45,.94) both}
    /* ----------------------------------------------
 * Generated by Animista on 2023-10-13 16:25:6
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes scale-in-center{0%{-webkit-transform:scale(0);transform:scale(0);opacity:1}100%{-webkit-transform:scale(1);transform:scale(1);opacity:1}}@keyframes scale-in-center{0%{-webkit-transform:scale(0);transform:scale(0);opacity:1}100%{-webkit-transform:scale(1);transform:scale(1);opacity:1}}
  


    .mButtons{
        display: flex;
        flex-direction: column;
        margin: 30px 0px;
    }
    .uprbtn,.lowbtn{
        display: flex;
    }
    a{text-decoration:none;
        display: flex;
        justify-content: center;
      color: white;
      margin: 20px 15px;
      font-size: 16px;
      font-family: sans-serif;
      background-color: #0f01478f;
      width:150px;
      padding: 10px 20px;
      border-radius: 5px;
      transition: 0.3s all;
      box-shadow: 2px 2px 4px  #f6f5f78f,-2px -2px 4px  #f6f5f78f,-2px 2px 4px  #f6f5f78f,2px -2px 4px  #f6f5f78f;
    }

    a:hover{
        background-color: #1d086d ;
    }
    .leftsection{
        display: flex;
        flex-direction: column;
        /* align-items: center; */
        justify-content: center;
        width: 600px;
        padding: 0 20px;
        color: white;
        font-size: 3rem;
        font-family: 'Signika Negative', sans-serif;
    }
    .aman{
        color: #9440e2;
    }
    .rightsection{
        width: 600px;
        height: 450px;
    }

    .rightsection>img{
        width: 80%;
    }
    .profile{
        color: #9440e2;
    }
    .intro{
        width: 70%;
        margin: 0 auto;
        color: white;
    }
    @media screen and (max-width: 650px){
        .rightsection>img{
            width: 70%;
        }
        .bodycontainer{
            flex-direction: column-reverse;
            align-items: center;
        }
        .leftsection{
            width: 100%;
            display: flex;
            align-items: center;
            padding: 0;
        }
        .rightsection{
            display: flex;
            justify-content: center;
        }
    }

    @media screen and (max-width: 600px){
        .rightsection{
            width:100%
        }
        .rightsection>img{
            width: 90%;
        }
        
    }
    @media screen and (max-width: 450px){
        .leftsection{
            font-size:2.3rem;
        }
        .uprbtn,.lowbtn{
            flex-direction: column;
        }
        a{
            margin: 15px;
        }
    }


`